# Generated by Django 4.0.5 on 2022-06-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jobtitle_siz_clothes_size_siz_clothes_type_siz_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='boss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.worker'),
        ),
    ]
