# Generated by Django 4.0.5 on 2022-06-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_issueditem_options_alter_jobtitle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='worker',
            name='patronymic',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='worker',
            name='surname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
