# Generated by Django 4.0.5 on 2022-06-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_worker_name_worker_patronymic_worker_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='siz',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(default='', help_text='Имя', max_length=200),
        ),
        migrations.AlterField(
            model_name='worker',
            name='patronymic',
            field=models.CharField(default='', help_text='Отчество', max_length=200),
        ),
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(default='', help_text='Фамилия', max_length=200),
        ),
    ]
