# Generated by Django 4.0.5 on 2022-06-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_siz_name_alter_worker_name_alter_worker_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterField(
            model_name='siz',
            name='clothes_type',
            field=models.CharField(choices=[('Руки', 'Руки'), ('Ноги', 'Ноги'), ('Общий', 'Общий'), ('Голова', 'Голова')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SIZOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('required_siz', models.ManyToManyField(to='main.siz')),
            ],
        ),
    ]
