# Generated by Django 4.0.5 on 2022-06-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_department_options_alter_siz_clothes_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='sizorder',
            name='required_siz',
        ),
        migrations.AddField(
            model_name='sizorder',
            name='required_siz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.siz'),
        ),
    ]
