# Generated by Django 4.0.5 on 2022-06-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_sizorder_quantity_remove_sizorder_required_siz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='issue_rate_notes',
            field=models.TextField(default=''),
        ),
    ]
