# Generated by Django 4.0.5 on 2022-06-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_worker_issued_clothes_delete_issueditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='issued_clothes',
        ),
        migrations.CreateModel(
            name='IssuedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('siz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siz')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker')),
            ],
            options={
                'verbose_name': 'Выделенная вещь',
                'verbose_name_plural': 'Выделенные вещи',
            },
        ),
    ]
