# Generated by Django 4.0.5 on 2022-06-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_worker_issued_clothes_issueditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='siz',
            name='issued_siz',
            field=models.ManyToManyField(through='main.IssuedItem', to='main.worker'),
        ),
    ]
