# Generated by Django 4.0.5 on 2022-06-15 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_remove_issueditem_date_remove_siz_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizorder',
            options={'verbose_name': 'Заказ СИЗ', 'verbose_name_plural': 'Заказы СИЗ'},
        ),
        migrations.AddField(
            model_name='siz',
            name='lifespan',
            field=models.IntegerField(default=12, verbose_name='Срок эксплуатации'),
        ),
        migrations.AlterField(
            model_name='department',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Начальник отдела'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='issueditem',
            name='expired_date',
            field=models.DateTimeField(null=True, verbose_name='Дата истечения срока годности'),
        ),
        migrations.AlterField(
            model_name='issueditem',
            name='issued_date',
            field=models.DateTimeField(null=True, verbose_name='Дата выдачи СИЗ'),
        ),
        migrations.AlterField(
            model_name='issueditem',
            name='siz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siz', verbose_name='СИЗ'),
        ),
        migrations.AlterField(
            model_name='issueditem',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='code',
            field=models.IntegerField(default=0, verbose_name='Код должности'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='issue_rate_notes',
            field=models.TextField(default='', verbose_name='Должностные инструкции'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='siz',
            name='clothes_size',
            field=models.FloatField(default=0, verbose_name='Размер СИЗ'),
        ),
        migrations.AlterField(
            model_name='siz',
            name='code',
            field=models.IntegerField(default=0, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='siz',
            name='issued_siz',
            field=models.ManyToManyField(through='main.IssuedItem', to='main.worker', verbose_name='Выделенный СИЗ'),
        ),
        migrations.AlterField(
            model_name='siz',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Название СИЗ'),
        ),
        migrations.AlterField(
            model_name='siz',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='siz',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='sizorder',
            name='date',
            field=models.DateTimeField(verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='sizorder',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='sizorder',
            name='required_siz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.siz', verbose_name='СИЗ'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='employment_start_date',
            field=models.DateTimeField(verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobtitle', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='patronymic',
            field=models.CharField(default='', max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='personnel_number',
            field=models.IntegerField(verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sex',
            field=models.CharField(max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='size_of_boots',
            field=models.FloatField(default=0, verbose_name='Размер обуви'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='size_of_clothes',
            field=models.FloatField(default=0, verbose_name='Размер одежды'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='size_of_hand',
            field=models.FloatField(default=0, verbose_name='Размер руки'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='size_of_head',
            field=models.FloatField(default=0, verbose_name='Размер головы'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(default='', max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись'),
        ),
    ]
