# Generated by Django 4.0.5 on 2022-06-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_sizorder_options_siz_lifespan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='issue_rate_notes',
        ),
        migrations.AlterField(
            model_name='siz',
            name='lifespan',
            field=models.IntegerField(default=12, verbose_name='Срок эксплуатации (мес.)'),
        ),
    ]
