# Generated by Django 4.0.5 on 2022-06-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_jobtitle_issue_rate_notes_alter_siz_lifespan'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='issue_rate_notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.siz', verbose_name='Нужные СИЗ'),
        ),
    ]
