# Generated by Django 4.0.5 on 2022-06-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_jobtitle_issue_rate_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='issue_rate_notes',
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='issue_rate_notes',
            field=models.ManyToManyField(blank=True, null=True, to='main.siz', verbose_name='Нужные СИЗ'),
        ),
    ]
