# Generated by Django 4.0.5 on 2022-06-15 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_jobtitle_issue_rate_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueditem',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobtitle', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='issueditem',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.worker', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='issue_rate_notes',
            field=models.ManyToManyField(blank=True, to='main.siz', verbose_name='Нужные СИЗ'),
        ),
    ]
