# Generated by Django 4.0.5 on 2022-06-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_issueditem_job_title_alter_issueditem_worker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='issue_rate_notes',
        ),
    ]
