# Generated by Django 4.0.5 on 2022-06-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_issuableitem_job_title_siz_issuable_siz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuableitem',
            options={'verbose_name': 'Выделяемая вещь', 'verbose_name_plural': 'Выделяемые вещи'},
        ),
        migrations.AddField(
            model_name='issuableitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='issueditem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
