# Generated by Django 4.0.5 on 2022-06-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_issuableitem_options_issuableitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueditem',
            name='issue_reason',
            field=models.CharField(default='Другое', max_length=1000, null=True, verbose_name='Причина выдачи'),
        ),
        migrations.AddField(
            model_name='issueditem',
            name='issued',
            field=models.CharField(choices=[('Заказано', 'Заказано'), ('Выдано', 'Выдано'), ('Израсходовано', 'Израсходовано')], max_length=200, null=True, verbose_name='Статус выданной вещи'),
        ),
    ]
