# Generated by Django 4.0.5 on 2022-06-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_issueditem_issue_reason_issueditem_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siz',
            name='clothes_size',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Размер СИЗ'),
        ),
        migrations.AlterField(
            model_name='siz',
            name='clothes_type',
            field=models.CharField(choices=[('Руки', 'Руки'), ('Ноги', 'Ноги'), ('Общий', 'Общий'), ('Голова', 'Голова'), ('Другое', 'Другое')], max_length=200, null=True),
        ),
    ]
