# Generated by Django 4.0.5 on 2022-06-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_siz_clothes_size_alter_siz_clothes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siz',
            name='clothes_type',
            field=models.CharField(choices=[('Руки', 'Руки'), ('Ноги', 'Ноги'), ('Общий', 'Общий'), ('Голова', 'Голова'), ('Другое', 'Другое')], max_length=200, null=True, verbose_name='Тип СИЗ'),
        ),
        migrations.AlterField(
            model_name='siz',
            name='lifespan',
            field=models.IntegerField(blank=True, default=12, null=True, verbose_name='Срок эксплуатации (мес.)'),
        ),
    ]
